from Tkinter import *

root = Tk()
root.wm_title("Vector Space Model")
topFrame = Frame(root)
topFrame.pack(side=TOP)
intro = Label(topFrame,text="IR ASSIGNMENT # 1\n Vector Space Model",bg="grey",fg="black")
intro.pack(fill=X)
midFrame = Frame(root)
midFrame.pack(side = TOP)
L1 = Label(midFrame, text = "Query")
L1.pack( side = LEFT)
E1 = Entry(midFrame,bd = 5)
E1.pack(side =RIGHT)
bottomFrame = Frame(root)
bottomFrame.pack(side=BOTTOM)
searchButton = Button(bottomFrame,text="Search")
searchButton.pack(side=LEFT)

root.mainloop()